# Generated by Django 4.0.4 on 2022-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(choices=[('N/A', 'N/A'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=3, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
