# Generated by Django 4.0.4 on 2022-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uadministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('N/A', 'N/A'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3, verbose_name='Codigo')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Asociada', 'Asociada'), ('Cliente', 'Cliente')], max_length=13, verbose_name='rol')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=10, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('tipo_documento', models.CharField(choices=[('C.C', 'C.C'), ('T.I', 'T.I'), ('C.E', 'C.E')], max_length=3, verbose_name='Tipo documento')),
            ],
        ),
    ]
