# Generated by Django 4.0.4 on 2022-04-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_talla', models.CharField(choices=[('Numero', 'Numero'), ('Letra', 'Letra')], max_length=8, verbose_name='Tipo talla')),
                ('nombre', models.CharField(max_length=10, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Asociada', 'Asociada'), ('Proveedor', 'Proveedor')], max_length=10, verbose_name='rol')),
                ('categoria', models.CharField(choices=[('Tejidos', 'Tejidos'), ('Ropa', 'Ropa'), ('Calzado', 'Calzado')], max_length=10, verbose_name='categoria')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('cantidad', models.CharField(max_length=100, unique=True)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.color', verbose_name='Color')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.marca', verbose_name='Marca')),
                ('talla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.talla', verbose_name='Talla')),
            ],
        ),
    ]
