# Generated by Django 4.0.4 on 2022-04-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_uadministrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de factura')),
                ('tipousuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor'), ('Asociada', 'Asociada')], max_length=10, verbose_name='Tipo de usuario')),
                ('producto', models.CharField(max_length=10, verbose_name='Producto')),
                ('cantidad', models.IntegerField()),
                ('tipofactura', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=10, verbose_name='Tipo de factura')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Nombre')),
            ],
        ),
    ]
