# Generated by Django 4.0.4 on 2022-05-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_cantidad'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipousuario',
            field=models.CharField(choices=[('Asociada', 'Asociada'), ('Proveedor', 'Proveedor')], max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
